"""Record which lines each test actually executes.

This is the whole basis of the tool: if a test never ran the line you changed, it cannot
have been affected by changing it. That is a real guarantee and a narrow one, and both
halves matter.

The map is built with `sys.settrace` from a pytest plugin of about sixty lines, written into
the repository under test and loaded with `-p`. No `coverage.py`, which keeps the runtime
dependency count at zero and, more usefully, keeps the semantics legible: a line is recorded
when a Python frame executes it, and nothing else is recorded at all.

## What that misses, stated plainly

**C code is invisible.** `settrace` fires for Python frames. A test that reaches changed
behaviour only through a compiled extension records nothing.

**Import-time execution belongs to whoever imported first.** Module-level code runs once, on
the first test that triggers the import, and every later test gets it for free. So a change
to a module-level constant is attributed to one arbitrary test. Changed *files* are therefore
treated as impacted wholesale, not just changed lines - see `select.py`.

**Dynamic dispatch is fine, and that is the point.** A registry lookup, a plugin hook, a
string-keyed table - none of it has to be understood, because the line either ran or it did
not. This is why the map is built by running rather than by reading imports.

**Parallel runs are not supported.** Under `pytest-xdist` the tracer would be installed per
worker and the per-test attribution would interleave. The plugin refuses rather than writing
a map that looks right.
"""

from __future__ import annotations

PLUGIN_NAME = "tio_tracer"
ENV_OUT = "TIO_TRACE_OUT"
ENV_ROOT = "TIO_TRACE_ROOT"

PLUGIN_SOURCE = '''\
# Generated by test-impact-oracle. Records, per test, the lines it executed.
import json
import os
import sys
import threading

import pytest

_OUT = os.environ.get("TIO_TRACE_OUT")
_ROOT = os.path.abspath(os.environ.get("TIO_TRACE_ROOT", "."))

_hits = {}
_current = None
_seen = None


# Directories that are never the project's own source, even when they sit inside it.
# A virtualenv usually does: `.venv/` lives at the repo root, so "is it under the root?"
# is not enough on its own. Tracing blast-radius without this gave 51 files and 1021
# lines per test, and all but a handful of them were pytest tracing itself.
#
# `build` and `dist` are deliberately NOT here. A repository can ship its package at
# `src/build/` - pypa/build does exactly that - and skipping a directory by name is how
# you end up reporting that a project has no source at all.
_SKIP = (
    ".venv", "venv", "site-packages", "node_modules", "__pycache__",
    ".tox", ".nox", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".git",
    ".eggs", "dist-info",
)


def _norm(path):
    try:
        p = os.path.abspath(path)
    except (TypeError, ValueError):
        return None
    # Only files inside the repository. Without this the map fills with the standard
    # library, which no diff will ever touch.
    if not p.startswith(_ROOT):
        return None
    rel = os.path.relpath(p, _ROOT).replace(os.sep, "/")
    parts = rel.split("/")
    for part in parts[:-1]:
        if part in _SKIP:
            return None
    if not rel.endswith(".py"):
        return None
    return rel


def _tracer(frame, event, arg):
    if _seen is None:
        return None
    if event == "line" or event == "call":
        rel = _norm(frame.f_code.co_filename)
        if rel is not None:
            _seen.add((rel, frame.f_lineno))
    return _tracer


def pytest_configure(config):
    if hasattr(config, "workerinput"):
        raise RuntimeError(
            "test-impact-oracle cannot trace under pytest-xdist: the tracer would be "
            "installed per worker and per-test attribution would interleave. "
            "Re-run without -n."
        )


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_protocol(item, nextitem):
    """Wrap the whole protocol, not just the call.

    Setup and teardown are where fixtures do their work, and a change inside a fixture has
    to select every test that uses it. Tracing only the call phase would miss all of them -
    and miss them silently, which is the failure mode that matters here: a test-selection
    tool that quietly drops tests is worse than no tool.
    """
    global _current, _seen
    _current = item.nodeid
    _seen = set()
    # threading.settrace catches threads the test starts; sys.settrace only covers this one.
    threading.settrace(_tracer)
    sys.settrace(_tracer)
    try:
        yield
    finally:
        sys.settrace(None)
        threading.settrace(None)
        _hits.setdefault(item.nodeid, set()).update(_seen or ())
        _seen = None
        _current = None


def pytest_sessionfinish(session, exitstatus):
    sys.settrace(None)
    if not _OUT:
        return
    data = {
        "root": _ROOT.replace(os.sep, "/"),
        "tests": {
            nodeid: sorted({f"{f}:{n}" for f, n in lines})
            for nodeid, lines in _hits.items()
        },
    }
    with open(_OUT, "w", encoding="utf-8") as fh:
        json.dump(data, fh)
'''
